# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_TIMER_OF)		+= timer-of.o
obj-$(CONFIG_TIMER_PROBE)	+= timer-probe.o
obj-$(CONFIG_X86_PM_TIMER)	+= acpi_pm.o
obj-$(CONFIG_CLKBLD_I8253)	+= i8253.o
obj-$(CONFIG_ARM_ARCH_TIMER)		+= arm_arch_timer.o
obj-$(CONFIG_ARCH_HAS_TICK_BROADCAST)	+= dummy_timer.o
