# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_ACPI_APEI)		+= apei.o
obj-$(CONFIG_ACPI_APEI_GHES)	+= ghes.o
obj-$(CONFIG_ACPI_APEI_PCIEAER)	+= ghes_helpers.o

apei-y := apei-base.o hest.o erst.o bert.o
