# SPDX-License-Identifier: GPL-2.0-only

# Branch profiling isn't noinstr-safe
subdir-ccflags-$(CONFIG_TRACE_BRANCH_PROFILING) += -DDISABLE_BRANCH_PROFILING

obj-y			+= kernel/ mm/ net/

# for cleaning
subdir- += boot
