# SPDX-License-Identifier: GPL-2.0

# Branch profiling isn't noinstr-safe.  Disable it for arch/x86/*
subdir-ccflags-$(CONFIG_TRACE_BRANCH_PROFILING) += -DDISABLE_BRANCH_PROFILING

obj-y += boot/startup/

obj-y += entry/

obj-$(CONFIG_PERF_EVENTS) += events/

obj-y += realmode/
obj-y += kernel/
obj-y += mm/

obj-y += platform/

obj-y += virt/

# for cleaning
subdir- += boot tools
