# SPDX-License-Identifier: GPL-2.0

# Branch profiling isn't noinstr-safe.  Disable it for arch/x86/*
subdir-ccflags-$(CONFIG_TRACE_BRANCH_PROFILING) += -DDISABLE_BRANCH_PROFILING

obj-y += boot/startup/

obj-y += entry/

obj-$(CONFIG_PERF_EVENTS) += events/

obj-y += realmode/
obj-y += kernel/
obj-y += mm/

obj-y += crypto/

obj-$(CONFIG_IA32_EMULATION) += ia32/

obj-y += platform/
obj-y += net/

obj-$(CONFIG_KEXEC_FILE) += purgatory/

obj-y += virt/

# for cleaning
subdir- += boot tools
