# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the linux kernel.
#
obj-$(CONFIG_ARM_SDE_INTERFACE)	+= arm_sdei.o
obj-$(CONFIG_DMI)		+= dmi_scan.o
obj-$(CONFIG_DMIID)		+= dmi-id.o
obj-$(CONFIG_FIRMWARE_MEMMAP)	+= memmap.o

obj-y				+= efi/
obj-y				+= psci/
obj-y				+= smccc/
