# SPDX-License-Identifier: GPL-2.0

context-analysis-cflags := -DWARN_CONTEXT_ANALYSIS		\
	-fexperimental-late-parse-attributes -Wthread-safety	\
	-Wthread-safety-pointer -Wthread-safety-beta

context-analysis-cflags += --warning-suppression-mappings=$(srctree)/scripts/context-analysis-suppression.txt

export CFLAGS_CONTEXT_ANALYSIS := $(context-analysis-cflags)
