# SPDX-License-Identifier: GPL-2.0

ifdef CONFIG_CC_IS_CLANG
kstack-erase-cflags-y += -fsanitize-coverage=stack-depth
DISABLE_KSTACK_ERASE  := -fno-sanitize-coverage=stack-depth
endif

KSTACK_ERASE_CFLAGS   := $(kstack-erase-cflags-y)

export KSTACK_ERASE_CFLAGS DISABLE_KSTACK_ERASE

KBUILD_CFLAGS += $(KSTACK_ERASE_CFLAGS)
