# SPDX-License-Identifier: GPL-2.0

randstruct-cflags-y += -DRANDSTRUCT

randstruct-cflags-y	\
	+= -frandomize-layout-seed-file=$(objtree)/scripts/basic/randstruct.seed

export RANDSTRUCT_CFLAGS := $(randstruct-cflags-y)

KBUILD_CFLAGS	+= $(RANDSTRUCT_CFLAGS)
