# SPDX-License-Identifier: GPL-2.0

# Enable available and selected Clang Propeller features.
ifdef CLANG_PROPELLER_PROFILE_PREFIX
  CFLAGS_PROPELLER_CLANG := -fbasic-block-sections=list=$(CLANG_PROPELLER_PROFILE_PREFIX)_cc_profile.txt -ffunction-sections
  KBUILD_LDFLAGS += --symbol-ordering-file=$(CLANG_PROPELLER_PROFILE_PREFIX)_ld_profile.txt --no-warn-symbol-ordering
else
  # Starting with Clang v20, the '-fbasic-block-sections=labels' option is
  # deprecated. Use the recommended '-fbasic-block-address-map' option.
  # Link: https://github.com/llvm/llvm-project/pull/110039
  ifeq ($(call clang-min-version, 200000),y)
    CFLAGS_PROPELLER_CLANG := -fbasic-block-address-map
  else
    CFLAGS_PROPELLER_CLANG := -fbasic-block-sections=labels
  endif
endif

# Propeller requires debug information to embed module names in the profiles.
CFLAGS_PROPELLER_CLANG += -gmlt

export CFLAGS_PROPELLER_CLANG
