# SPDX-License-Identifier: GPL-2.0

# Shared with KVM/arm64.
export CFLAGS_UBSAN_TRAP := $(call cc-option,-fsanitize-trap=undefined,-fsanitize-undefined-trap-on-error)

# Enable available and selected UBSAN features.

export CFLAGS_UBSAN := $(ubsan-cflags-y)

	-DINTEGER_WRAP						\
	-fsanitize-undefined-ignore-overflow-pattern=all	\
	-fsanitize=signed-integer-overflow			\
	-fsanitize=unsigned-integer-overflow			\
	-fsanitize=implicit-signed-integer-truncation		\
	-fsanitize=implicit-unsigned-integer-truncation		\
	-fsanitize-ignorelist=$(srctree)/scripts/integer-wrap-ignore.scl
export CFLAGS_UBSAN_INTEGER_WRAP := $(ubsan-integer-wrap-cflags-y)
