DEBUG_CFLAGS	:=
DEBUG_RUSTFLAGS	:=

debug-flags-y	:= -g

DEBUG_CFLAGS	+= $(debug-flags-y)
KBUILD_AFLAGS	+= $(debug-flags-y)

ifdef CONFIG_DEBUG_INFO_REDUCED
DEBUG_CFLAGS	+= -fno-var-tracking
DEBUG_RUSTFLAGS	+= -Cdebuginfo=1
ifdef CONFIG_CC_IS_GCC
DEBUG_CFLAGS	+= -femit-struct-debug-baseonly
endif
else
DEBUG_RUSTFLAGS	+= -Cdebuginfo=2
endif

KBUILD_CFLAGS	+= $(DEBUG_CFLAGS)
export DEBUG_CFLAGS

KBUILD_RUSTFLAGS += $(DEBUG_RUSTFLAGS)
export DEBUG_RUSTFLAGS
